name: Run 1.py Script

on:
  # 触发条件：每隔5分钟执行一次
  schedule:
    - cron: '*/120 * * * *'
  # 允许手动触发
  workflow_dispatch:
  # 触发条件：当代码被推送到main分支时
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install shutil
        pip install zipfile
        pip install bs4 
        pip install requests.packages.urllib3.exceptions 

    - name: Run 1.py script
      run: python 1.py
