name: Run 1.py Script

on:
  # 触发条件：每隔5分钟执行一次
  schedule:
    - cron: '*/5 * * * *'
  # 允许手动触发
  workflow_dispatch:
  # 触发条件：当代码被推送到main分支时
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4

    - name: Run 1.py script
      id: run-script
      run: |
        python 1.py
        # 输出文件路径和版本号
        echo "file_path=$(cat file_path.txt)" >> $GITHUB_OUTPUT
        echo "version_number=$(cat version_number.txt)" >> $GITHUB_OUTPUT

    - name: Upload to release
      if: steps.run-script.outputs.file_path != ''
      env:
        FILE_PATH: ${{ steps.run-script.outputs.file_path }}
        VERSION_NUMBER: ${{ steps.run-script.outputs.version_number }}
      run: |
        # 使用 GitHub CLI (gh) 上传文件
        gh release create "v${VERSION_NUMBER}" "${FILE_PATH}" --title "Release v${VERSION_NUMBER}" --notes "New release."
      # 安装 gh CLI
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'  # gh CLI 需要 Go 环境
      run: |
        go install github.com/cli/cli@latest
